package simplechessclient;

import javafx.beans.property.StringProperty;
import javafx.beans.value.ObservableValue;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

public class GameWindows {
    static class TimeWindow extends JFrame {
        /** Creates new form Antenna */
        public TimeWindow(StringProperty sp) {
            initComponents(sp);
        }

        /** This method is called from within the constructor to
         * initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents(StringProperty sp) {
            jLabel = new JLabel();
            
            sp.addListener((ObservableValue<? extends String> observable, String oldValue, String newValue) -> {
                jLabel.setText(newValue);
            });

            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
            setTitle("Timers");
            setAlwaysOnTop(true);

            jLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
            jLabel.setText("1+0");
            jLabel.setToolTipText("");

            GroupLayout layout = new GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>

        // Variables declaration - do not modify                     
        private JLabel jLabel;
        // End of variables declaration                   
    }

    public static JFrame showTimeWindow(StringProperty sp) {
        //<editor-fold defaultstate="collapsed" desc="Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.LookAndFeelInfo[] installedLookAndFeels=UIManager.getInstalledLookAndFeels();
            for(UIManager.LookAndFeelInfo installedLookAndFeel : installedLookAndFeels) {
                if("Nimbus".equals(installedLookAndFeel.getName())) {
                    UIManager.setLookAndFeel(installedLookAndFeel.getClassName());
                    break;
                }
            }
        } catch(ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        JFrame frame = new GameWindows.TimeWindow(sp);
        
        java.awt.EventQueue.invokeLater(() -> {
            frame.setVisible(true);
        });
        
        return frame;
    }
}