package simplechessclient;

import java.awt.Dimension;
import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.LayoutStyle;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

/**
 * A class that contains windows that come up during the game
 * @author Jed Wang
 */
public class GameWindows {
    /**
     * A Window that contains the time control of the game.
     */
    private static class TimeWindow extends JFrame {
        /** 
         * Creates new form TimeWindow. 
         * @param tc the TimeControl
         */
        public TimeWindow(TimeControl tc) {
            initComponents(tc);
        }

        /** This method is called from within the constructor to
         * initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents(TimeControl tc) {
            jLabel = new JLabel();
            
            tc.addChangeListener(
                    (ChangeListener) (ObservableValue observable, Object oldValue, Object newValue) -> {
                jLabel.setText(tc.toString());
            });

            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
            setTitle("Timers");
            setAlwaysOnTop(true);
            setResizable(false);

            jLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
            jLabel.setText("0:00.0|0:00.0");
            jLabel.setToolTipText("");

            GroupLayout layout = new GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>
        
        private JLabel jLabel;                
    }

    /**
     * Creates and shows a TimeWindow
     * @param tc the TimeControl
     * @return the TimeWindow
     */
    public static JFrame showTimeWindow(TimeControl tc) {
        //<editor-fold defaultstate="collapsed" desc="Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.LookAndFeelInfo[] installedLookAndFeels=UIManager.getInstalledLookAndFeels();
            for(UIManager.LookAndFeelInfo installedLookAndFeel : installedLookAndFeels) {
                if("Nimbus".equals(installedLookAndFeel.getName())) {
                    UIManager.setLookAndFeel(installedLookAndFeel.getClassName());
                    break;
                }
            }
        } catch(ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        JFrame frame = new GameWindows.TimeWindow(tc);
        frame.setSize(277, frame.getHeight());
        
        java.awt.EventQueue.invokeLater(() -> {
            frame.setVisible(true);
        });
        
        System.out.println("(" + frame.getWidth() + ")");
        
        return frame;
    }
    
    /**
     * A Window that displays the name of you or your opponent.
     */
    private static class NameWindow extends javax.swing.JFrame {
    
        /** Creates new form NameWindow */
        public NameWindow(String name, boolean isYou) {
            initComponents(name, isYou);
        }

        /** This method is called from within the constructor to
         * initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents(String name, boolean isYou) {
            nameLabel = new javax.swing.JLabel();
            isYouLabel = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("Name");
            setAlwaysOnTop(true);
            setResizable(false);

            nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
            nameLabel.setText(name);
            nameLabel.setToolTipText("");

            isYouLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
            isYouLabel.setText(isYou?"You:":"Opponent:");

            GroupLayout layout = new GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(isYouLabel)
                        .addComponent(nameLabel))
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(isYouLabel)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(nameLabel)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            
            pack();
        }// </editor-fold>

        // Variables declaration - do not modify                     
        private javax.swing.JLabel isYouLabel;
        private javax.swing.JLabel nameLabel;
        // End of variables declaration                   
    }

    /**
     * Creates and shows a TimeWindow
     * @param name the name of the player
     * @param isYou whether this player is you
     * @return the TimeWindow
     */
    public static JFrame showNameWindow(String name, boolean isYou) {
        //<editor-fold defaultstate="collapsed" desc="Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.LookAndFeelInfo[] installedLookAndFeels=UIManager.getInstalledLookAndFeels();
            for(UIManager.LookAndFeelInfo installedLookAndFeel : installedLookAndFeels) {
                if("Nimbus".equals(installedLookAndFeel.getName())) {
                    UIManager.setLookAndFeel(installedLookAndFeel.getClassName());
                    break;
                }
            }
        } catch(ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        JFrame frame = new GameWindows.NameWindow(name, isYou);
        if(frame.getWidth() < 220) {
            frame.setSize(220, frame.getHeight());
        }
        
        java.awt.EventQueue.invokeLater(() -> {
            frame.setVisible(true);
        });
        
        return frame;
    }
}