package simplechessclient;

import java.awt.Component;
import java.awt.Container;
import javafx.beans.property.StringProperty;
import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import javax.swing.AbstractButton;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

/**
 * A class that contains windows that come up during the game
 * @author Jed Wang
 */
public class GameWindows {
    /**
     * A Window that contains the time control of the game.
     */
    private static class TimeWindow extends JFrame {
        /** 
         * Creates new form TimeWindow. 
         * @param tc the TimeControl
         */
        public TimeWindow(TimeControl tc) {
            initComponents(tc);
        }

        /** This method is called from within the constructor to
         * initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents(TimeControl tc) {
            jLabel = new JLabel();
            
            tc.addChangeListener(
                    (ChangeListener) (ObservableValue observable, Object oldValue, Object newValue) -> {
                jLabel.setText(tc.toString());
            });

            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
            setTitle("Timers");
            setAlwaysOnTop(true);
            setResizable(false);

            jLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
            jLabel.setText(tc.toString());
            jLabel.setToolTipText("");

            GroupLayout layout = new GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>
        
        private JLabel jLabel;                
    }

    /**
     * Creates and shows a TimeWindow
     * @param tc the TimeControl
     * @return the TimeWindow
     */
    public static JFrame showTimeWindow(TimeControl tc) {
        //<editor-fold defaultstate="collapsed" desc="Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.LookAndFeelInfo[] installedLookAndFeels=UIManager.getInstalledLookAndFeels();
            for(UIManager.LookAndFeelInfo installedLookAndFeel : installedLookAndFeels) {
                if("Nimbus".equals(installedLookAndFeel.getName())) {
                    UIManager.setLookAndFeel(installedLookAndFeel.getClassName());
                    break;
                }
            }
        } catch(ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        JFrame frame = new GameWindows.TimeWindow(tc);
        
        java.awt.EventQueue.invokeLater(() -> {
            removeMinMaxClose(frame);
            frame.setVisible(true);
        });
        
        return frame;
    }
    
    /**
     * Removes the minimize, maximize, and close buttons from the Component
     * @param comp the Component to alter
     */
    public static void removeMinMaxClose(Component comp) {
        if(comp instanceof AbstractButton) {
            comp.getParent().remove(comp);
        }
        if(comp instanceof Container) {
            Component[] comps = ((Container)comp).getComponents();
            for(int x = 0, y = comps.length; x < y; x++) {
                removeMinMaxClose(comps[x]);
            }
        }
    }
}